---
- name: instance creation
  ec2:
    key_name: "{{ ec2.keypair }}"
    region: "{{ ec2.region }}"
    instance_tags: "{{ ec2.tags }}"
    image: "{{ ec2.image }}"
    instance_type: "{{ ec2.instance_type }}"
    instance_profile_name: "{{ ec2.role | default('') }}"
    vpc_subnet_id: "{{ ec2.subnet }}"
    assign_public_ip: "{{ ec2.public_ip | default('') }}"
    group: "{{ ec2.sg }}"
    wait: True
  register: ec2

# - debug: var=hostvars[inventory_hostname]
# - debug: msg="{{ hostvars[inventory_hostname]['ec2'] }}"
- add_host: 
    name: "{{ item.public_ip }}" 
    groups: new_node
    ansible_user: openvpnas
  with_items: "{{ ec2.instances }}"